name: hereandnow
favicon: null
layout_spectrum: 0.8601510638836771
typography_spectrum: 0.3688796916976571
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5276364146266133
  lightness: 0.5528484671376646
  saturation: 0.21412012516520917
  rhythmicContrast: 0.6104544303379953
purpose: []
