name: hereandnow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34541
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5a5551'
    - '#877f7c'
    - '#b2adaa'
    - '#ded4d2'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
